<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        if (app()->environment(['local', 'testing'])) {
            $adminEmail = env('ADMIN_EMAIL', 'admin@gmail.com');

            if (! User::query()->where('email', $adminEmail)->exists()) {
                User::factory()->create([
                    'name' => 'Admin',
                    'email' => $adminEmail,
                    'password' => env('ADMIN_PASSWORD', 'password'),
                    'is_admin' => true,
                ]);
            }
        }

        User::factory()->create([
            'name' => 'Test User',
            'email' => 'test@example.com',
        ]);

        $categories = collect(['Sneakers', 'Running Shoes', 'Wallets'])
            ->mapWithKeys(fn (string $name) => [$name => Category::create([
                'name' => $name,
                'slug' => Str::slug($name),
            ])]);

        $brands = collect(['Nike', 'Adidas', 'New Balance', 'Puma', 'Vint-Edge'])
            ->mapWithKeys(fn (string $name) => [$name => Brand::create([
                'name' => $name,
                'slug' => Str::slug($name),
            ])]);

        $products = [
            [
                'name' => 'J-1 Traviscoot Olive',
                'slug' => 'j-1-traviscoot-olive-273',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'J-1 Traviscoot Olive by Nike — part of the Vint-Edge collection.',
                'original_price' => 4500,
                'discount_price' => 3150,
                'discount_percentage' => 30,
                'is_featured' => true,
                'is_trending' => true,
                'release_date' => now()->subDays(5),
                'image' => '/images/products/273.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [25, 22, 23, 24, 26],
            ],
            [
                'name' => 'SB Dunk Low "J-Pack Shadow"',
                'slug' => 'sb-dunk-low-j-pack-shadow-272',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'The Nike SB Dunk Low "J-Pack - Shadow" sees the return of Air Jordan 1 inspired color blocking as part of Nike\'s Dunk revolution in 2020. After the initial "J-Pack", which stands for "Jordan Pack ", from 2005 which included the "Bred" and "Royal" looks for the Dunk, Nike SB shows more nostalgia on this colorway which is undoubtedly inspired by the Air Jordan 1 "Shadow". The construction features a black leather and nubuck upper with a perforated gray leather toe and gray nubuck Swooshes. Other styling cues are present, like gray laces and Nike embroidery on the heel, and a puffy black mesh padded tongue for impact protection. Release date: Spring 2020.',
                'original_price' => 4500,
                'discount_price' => 3150,
                'discount_percentage' => 30,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(10),
                'image' => '/images/products/272.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [5, 7, 8, 7, 5],
            ],
            [
                'name' => 'J-1 Low Mocha OEM',
                'slug' => 'j-1-low-mocha-oem-271',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'Building off the success of their previous collaborations, Travis Scott adds yet another new design to his collaborative relationship with Jumpman via the Air Jordan 1 Low Travis Scott. This AJ 1 Low features a black upper with dark brown overlays and red accents on the branding, La Flame\'s signature backwards Swoosh logo on the lateral side, and "Cactus Jack" insignias on the heel atop a sail midsole and dark brown outsole.',
                'original_price' => 4500,
                'discount_price' => 3150,
                'discount_percentage' => 30,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(15),
                'image' => '/images/products/271.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [9, 5, 8, 10, 10],
            ],
            [
                'name' => 'SB Dunk Low "Year of the Dragon Steam Puppet"',
                'slug' => 'sb-dunk-low-year-of-the-dragon-steam-puppet-270',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'Inspired by the elegance and strength of the legendary dragon, this Dunk Low combines eye-catching aesthetics with everyday comfort. Featuring a unique dragon-scale textured upper, icy blue wave-inspired detailing, and a clean white base, cushioned insole, and durable rubber outsole.',
                'original_price' => 4800,
                'discount_price' => 3360,
                'discount_percentage' => 30,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(20),
                'image' => '/images/products/270.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [3, 3, 3, 2, 2],
            ],
            [
                'name' => 'AF-1 Dark Sky Blue',
                'slug' => 'af-1-dark-sky-blue-268',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'Step into effortless style with the Nike Air Force 1 Blue Suede — a perfect blend of classic heritage and modern streetwear vibes. The premium suede upper in a rich blue tone delivers a soft, luxurious feel, built on the iconic Air Force 1 silhouette with encapsulated Air cushioning.',
                'original_price' => 4800,
                'discount_price' => 3360,
                'discount_percentage' => 30,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(25),
                'image' => '/images/products/268.webp',
                'sizes' => ['41', '42', '43', '44', '45', '46'],
                'stock' => [1, 1, 1, 1, 1, 1],
            ],
            [
                'name' => 'Air Jordan 1 Panda High',
                'slug' => 'air-jordan-1-panda-high-267',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'A classic high-top sneaker that leans heavily into a timeless, minimalist aesthetic, with a striking high-contrast colorway that makes it incredibly versatile for both streetwear and more polished looks.',
                'original_price' => 3600,
                'discount_price' => 2160,
                'discount_percentage' => 40,
                'is_featured' => true,
                'is_trending' => true,
                'release_date' => now()->subDays(30),
                'image' => '/images/products/267.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [4, 3, 3, 4, 4],
            ],
            [
                'name' => 'Air Force 1 Tripple White OEM',
                'slug' => 'air-force-1-tripple-white-oem-265',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'Step into timeless style with the iconic Nike Air Force 1 Low. Designed with a clean all-white finish, this sneaker delivers the perfect blend of classic streetwear aesthetics and everyday comfort, crafted with premium synthetic leather.',
                'original_price' => 3900,
                'discount_price' => 2730,
                'discount_percentage' => 30,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(35),
                'image' => '/images/products/265.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [1, 1, 1, 1, 1],
            ],
            [
                'name' => 'Air Force 1 Low Waterproof "Triple Black"',
                'slug' => 'air-force-1-low-waterproof-triple-black-264',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'Air Force 1 Low Waterproof "Triple Black" by Nike — part of the Vint-Edge collection.',
                'original_price' => 3000,
                'discount_price' => 1800,
                'discount_percentage' => 40,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(40),
                'image' => '/images/products/264.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [1, 1, 1, 1, 1],
            ],
            [
                'name' => 'Air Jordan 1 Low Green OEM',
                'slug' => 'air-jordan-1-low-green-oem-263',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'A standout pair that blends classic basketball heritage with fresh street-ready energy, featuring a sharp mix of black and white leather accented by vibrant green details, a perforated toe box, and a cushioned midsole.',
                'original_price' => 4800,
                'discount_price' => 2880,
                'discount_percentage' => 40,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(45),
                'image' => '/images/products/263.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [0, 0, 0, 0, 0],
            ],
            [
                'name' => 'Airforce 1 Tripple White Supreme OEM',
                'slug' => 'airforce-1-tripple-white-supreme-oem-262',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'The iconic Nike Air Force 1 Low x Supreme. This clean white silhouette is elevated with bold red accents, featuring Supreme\'s signature box logo on the heel and eye-catching red laces.',
                'original_price' => 3900,
                'discount_price' => 2340,
                'discount_percentage' => 40,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(50),
                'image' => '/images/products/262.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [0, 0, 0, 0, 0],
            ],
            [
                'name' => 'J-1 Low Williamson Voodoo Zion',
                'slug' => 'j-1-low-williamson-voodoo-zion-261',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'This pair stands out for its patchwork design and mixed materials, combining canvas, suede, and textured fabrics in earthy tones. A mini reversed Swoosh on the toe, exposed stitching, and Voodoo-inspired graphics give it a raw, artistic feel.',
                'original_price' => 3900,
                'discount_price' => 2730,
                'discount_percentage' => 30,
                'is_featured' => true,
                'is_trending' => true,
                'release_date' => now()->subDays(55),
                'image' => '/images/products/261.png',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [5, 5, 6, 7, 8],
            ],
            [
                'name' => 'Air Jordan 1 "Mocha"',
                'slug' => 'air-jordan-1-mocha-260',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'Air Jordan 1 Low OG "Mocha" — a muted, premium colorway built on the classic low-top silhouette.',
                'original_price' => 3200,
                'discount_price' => 2100,
                'discount_percentage' => 34,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(60),
                'image' => '/images/products/260.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [0, 0, 0, 0, 0],
            ],
            [
                'name' => 'J-1 Low "Milan"',
                'slug' => 'j-1-low-milan-259',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'Inspired by Milan\'s luxury fashion culture, this Air Jordan 1 Low blends premium craftsmanship with timeless Jordan heritage — smooth leather and soft suede in elegant neutral tones with subtle peach accents.',
                'original_price' => 3000,
                'discount_price' => 2100,
                'discount_percentage' => 30,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(65),
                'image' => '/images/products/259.png',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [20, 8, 9, 16, 15],
            ],
            [
                'name' => 'Air Jordan 1 Black Panda',
                'slug' => 'air-jordan-1-black-panda-258',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'A timeless icon refreshed in a sleek black-and-white colorway. Built with premium leather, durable stitching, and signature Air cushioning for all-day comfort with a stylish edge.',
                'original_price' => 3000,
                'discount_price' => 1500,
                'discount_percentage' => 49.99,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(70),
                'image' => '/images/products/258.png',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [2, 1, 1, 1, 3],
            ],
            [
                'name' => 'Air Jordan 1 Retro High "Black Toe"',
                'slug' => 'air-jordan-1-retro-high-black-toe-257',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'A timeless classic that defines sneaker culture. Premium leather upper with the iconic black toe box, white panels, and bold Varsity Red accents, finished with the legendary Wings logo.',
                'original_price' => 3300,
                'discount_price' => 1980,
                'discount_percentage' => 40,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(75),
                'image' => '/images/products/257.png',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [0, 0, 0, 0, 0],
            ],
            [
                'name' => 'Nike Air Jordan 1 Panda',
                'slug' => 'nike-air-jordan-1-panda-256',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'A clean, versatile look with classic street-style appeal — crisp white leather base with bold black overlays, perforated toe box, and signature Air cushioning.',
                'original_price' => 3000,
                'discount_price' => 1800,
                'discount_percentage' => 40,
                'is_featured' => true,
                'is_trending' => true,
                'release_date' => now()->subDays(80),
                'image' => '/images/products/256.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [1, 1, 1, 1, 1],
            ],
            [
                'name' => 'Air Jordan 1 High Dior',
                'slug' => 'air-jordan-1-high-dior-251',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'An ultra-exclusive collaboration blending high fashion and iconic sneaker culture. Timeless silhouette crafted from premium Italian leather, featuring the signature Oblique pattern on the Swoosh.',
                'original_price' => 3700,
                'discount_price' => 2220,
                'discount_percentage' => 40,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(85),
                'image' => '/images/products/251.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [0, 0, 0, 0, 0],
            ],
            [
                'name' => 'Adidas Samba OG',
                'slug' => 'adidas-samba-og-249',
                'brand' => 'Adidas',
                'category' => 'Sneakers',
                'description' => 'The classic look that has been loved for decades. Designed originally for indoor football, now a global street-style icon, with a smooth leather upper, suede toe overlay, and signature gum sole.',
                'original_price' => 3300,
                'discount_price' => 1980,
                'discount_percentage' => 40,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(90),
                'image' => '/images/products/249.webp',
                'sizes' => ['41', '42', '43', '44', '45'],
                'stock' => [0, 0, 0, 0, 0],
            ],
            [
                'name' => 'Nike Air Jordan 1 Mid "Barely Orange"',
                'slug' => 'nike-air-jordan-1-mid-barely-orange-248',
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'description' => 'Nike Air Jordan 1 Mid "Barely Orange" — a soft, wearable mid-top colorway built for everyday rotation.',
                'original_price' => 3300,
                'discount_price' => 2640,
                'discount_percentage' => 20,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(95),
                'image' => '/images/products/248.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [0, 0, 0, 0, 0],
            ],
            [
                'name' => 'New Balance 9060 OEM',
                'slug' => 'new-balance-9060-oem-269',
                'brand' => 'New Balance',
                'category' => 'Running Shoes',
                'description' => 'Blends retro heritage with futuristic design, one of the most eye-catching sneakers in the modern streetwear scene. Inspired by the iconic 99X series with a bold Y2K aesthetic and sculpted lines.',
                'original_price' => 4200,
                'discount_price' => 2520,
                'discount_percentage' => 40,
                'is_featured' => false,
                'is_trending' => true,
                'release_date' => now()->subDays(100),
                'image' => '/images/products/269.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [1, 1, 1, 1, 1],
            ],
            [
                'name' => 'Adidas Adizero Evo SL OEM',
                'slug' => 'adidas-adizero-evo-sl-oem-245',
                'brand' => 'Adidas',
                'category' => 'Running Shoes',
                'description' => 'Ultra-light speed for runners who want maximum performance — breathable mesh upper, responsive cushioning, and a feather-light build that boosts your stride.',
                'original_price' => 4550,
                'discount_price' => 3640,
                'discount_percentage' => 20,
                'is_featured' => true,
                'is_trending' => true,
                'release_date' => now()->subDays(105),
                'image' => '/images/products/245.webp',
                'sizes' => ['40', '41', '42', '43', '44'],
                'stock' => [0, 0, 0, 0, 0],
            ],
        ];

        foreach ($products as $data) {
            $product = Product::create([
                'category_id' => $categories[$data['category']]->id,
                'brand_id' => $brands[$data['brand']]->id,
                'name' => $data['name'],
                'slug' => $data['slug'],
                'description' => $data['description'],
                'original_price' => $data['original_price'],
                'discount_price' => $data['discount_price'],
                'discount_percentage' => $data['discount_percentage'],
                'images' => [$data['image']],
                'is_featured' => $data['is_featured'],
                'is_trending' => $data['is_trending'],
                'release_date' => $data['release_date'],
            ]);

            foreach (array_map(null, $data['sizes'], $data['stock']) as [$size, $stockQuantity]) {
                $product->variants()->create([
                    'size' => $size,
                    'stock_quantity' => $stockQuantity,
                ]);
            }
        }
    }
}
